name: Update README Stats Card

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/readme-stats.yml'

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub stats SVG
        uses: cicirello/user-statistician@v1
        with:
          colors: dark
          image-file: assets/github-stats.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
